# Generated by Django 4.1.2 on 2022-11-27 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("class", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationtoclass",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="classdates",
            name="class_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="class.class"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.course"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="class.registrationsettings",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="rooms",
            field=models.ManyToManyField(to="room.room"),
        ),
        migrations.AddField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(
                through="class.RegistrationToClass", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="class.typeofclass"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="entered_points_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="evaluated_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="class.class"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="registrationtoclass",
            unique_together={("class_id", "user")},
        ),
    ]
