# Generated by Django 4.1.2 on 2022-11-27 15:35

import course.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "shortcut",
                    models.CharField(
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                        validators=[course.models.validate_course_name],
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=1000)),
                (
                    "price",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(180),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=1000)),
                ("date", models.DateTimeField()),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="RegistrationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mandatory", models.BooleanField(default=False)),
                ("auto_approve", models.BooleanField(default=True)),
                ("capacity", models.IntegerField(null=True)),
                ("opens", models.DateTimeField()),
                ("closes", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TypeOfCourse",
            fields=[
                (
                    "shortcut",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="RegistrationToCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted", models.BooleanField(default=1)),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
            ],
        ),
    ]
